/*
###############################################################
#  Generated by:      Cadence Encounter 13.13-s017_1
#  OS:                Linux x86_64(Host ID lab1-29)
#  Generated on:      Thu Nov 20 21:14:58 2014
#  Design:            controller
#  Command:           saveNetlist controller_edi.v
###############################################################
*/
module controller (
	clk, 
	reset, 
	op, 
	zero, 
	memread, 
	memwrite, 
	alusrca, 
	memtoreg, 
	iord, 
	pcen, 
	regwrite, 
	regdst, 
	pcsource, 
	alusrcb, 
	aluop, 
	irwrite);
   input clk;
   input reset;
   input [5:0] op;
   input zero;
   output memread;
   output memwrite;
   output alusrca;
   output memtoreg;
   output iord;
   output pcen;
   output regwrite;
   output regdst;
   output [1:0] pcsource;
   output [1:0] alusrcb;
   output [1:0] aluop;
   output [3:0] irwrite;

   // Internal wires
   wire clk__L2_N1;
   wire clk__L2_N0;
   wire clk__L1_N0;
   wire FE_OFN0_pcsource_0_;
   wire n1;
   wire n3;
   wire n7;
   wire n20;
   wire n103;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n143;
   wire n145;
   wire n148;
   wire n149;
   wire n151;
   wire n153;
   wire n155;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire [3:0] state;

   INVX8 clk__L2_I1 (.Y(clk__L2_N1),
	.A(clk__L1_N0));
   INVX8 clk__L2_I0 (.Y(clk__L2_N0),
	.A(clk__L1_N0));
   INVX8 clk__L1_I0 (.Y(clk__L1_N0),
	.A(clk));
   BUFX4 FE_OFC0_pcsource_0_ (.Y(pcsource[0]),
	.A(FE_OFN0_pcsource_0_));
   DFF2 state_reg_1_ (.QB(state[1]),
	.D(n20),
	.CLRB(n7),
	.CLK(clk__L2_N1));
   DFF2 state_reg_3_ (.QB(state[3]),
	.D(n3),
	.CLRB(n7),
	.CLK(clk__L2_N1));
   DFF2 state_reg_2_ (.QB(state[2]),
	.D(n1),
	.CLRB(n7),
	.CLK(clk__L2_N0));
   DFF2 state_reg_0_ (.QB(n124),
	.Q(state[0]),
	.D(n192),
	.CLRB(n7),
	.CLK(clk__L2_N0));
   TIEHI U120 (.Y(n7));
   NAND2X1 U121 (.Y(iord),
	.B(n143),
	.A(n200));
   INVX1 U122 (.Y(n143),
	.A(memwrite));
   NAND2X1 U123 (.Y(regwrite),
	.B(n134),
	.A(n137));
   INVX1 U124 (.Y(n134),
	.A(memtoreg));
   NAND2X1 U127 (.Y(n137),
	.B(n136),
	.A(n135));
   INVX1 U128 (.Y(n136),
	.A(n170));
   NAND2X1 U129 (.Y(n135),
	.B(n168),
	.A(n169));
   BUFX4 U130 (.Y(aluop[0]),
	.A(pcsource[0]));
   NAND2X1 U131 (.Y(alusrcb[1]),
	.B(n186),
	.A(n193));
   NAND2X1 U133 (.Y(alusrca),
	.B(n186),
	.A(n161));
   NAND2X1 U135 (.Y(alusrcb[0]),
	.B(n193),
	.A(n182));
   NAND2X1 U136 (.Y(pcen),
	.B(n167),
	.A(n182));
   INVX1 U137 (.Y(n167),
	.A(n140));
   NAND2X1 U138 (.Y(n140),
	.B(n139),
	.A(n138));
   INVX1 U139 (.Y(n139),
	.A(pcsource[1]));
   NAND2X1 U141 (.Y(n138),
	.B(pcsource[0]),
	.A(zero));
   NAND2X1 U142 (.Y(n166),
	.B(n177),
	.A(state[3]));
   NAND2X1 U144 (.Y(memread),
	.B(n200),
	.A(n182));
   NAND2X1 U145 (.Y(n164),
	.B(n107),
	.A(n141));
   INVX1 U147 (.Y(n141),
	.A(irwrite[1]));
   INVX1 U148 (.Y(n202),
	.A(n111));
   NAND2X1 U149 (.Y(n111),
	.B(n181),
	.A(n109));
   NAND2X1 U151 (.Y(n109),
	.B(n200),
	.A(n201));
   NAND2X1 U152 (.Y(n200),
	.B(n163),
	.A(n172));
   INVX1 U153 (.Y(n163),
	.A(n162));
   INVX1 U154 (.Y(n201),
	.A(n114));
   NAND2X1 U155 (.Y(n114),
	.B(n113),
	.A(n112));
   INVX1 U156 (.Y(n113),
	.A(aluop[1]));
   NAND2X1 U157 (.Y(n170),
	.B(state[1]),
	.A(state[3]));
   NAND2X1 U158 (.Y(n112),
	.B(n198),
	.A(n199));
   NAND2X1 U159 (.Y(n192),
	.B(n190),
	.A(n191));
   INVX1 U160 (.Y(n185),
	.A(n120));
   NAND2X1 U161 (.Y(n120),
	.B(n119),
	.A(n118));
   INVX1 U162 (.Y(n119),
	.A(n184));
   NAND2X1 U163 (.Y(n118),
	.B(n204),
	.A(op[2]));
   INVX1 U164 (.Y(n153),
	.A(n199));
   INVX1 U166 (.Y(n189),
	.A(n125));
   NAND2X1 U167 (.Y(n125),
	.B(n124),
	.A(n123));
   NAND2X1 U168 (.Y(n123),
	.B(state[2]),
	.A(state[1]));
   INVX1 U169 (.Y(n151),
	.A(n210));
   INVX1 U170 (.Y(n203),
	.A(n117));
   NAND2X1 U171 (.Y(n117),
	.B(n116),
	.A(n115));
   INVX1 U172 (.Y(n116),
	.A(n197));
   NAND2X1 U173 (.Y(n197),
	.B(n195),
	.A(n196));
   NAND2X1 U174 (.Y(n115),
	.B(op[1]),
	.A(op[2]));
   INVX1 U175 (.Y(n209),
	.A(n105));
   NAND2X1 U176 (.Y(n105),
	.B(n181),
	.A(n103));
   NAND2X1 U178 (.Y(n103),
	.B(n207),
	.A(n208));
   NAND2X1 U181 (.Y(n108),
	.B(n107),
	.A(n106));
   INVX1 U182 (.Y(n107),
	.A(irwrite[3]));
   INVX1 U183 (.Y(n159),
	.A(n173));
   NAND2X1 U184 (.Y(n106),
	.B(n204),
	.A(n205));
   NAND2X1 U185 (.Y(n204),
	.B(n122),
	.A(n121));
   INVX1 U186 (.Y(n122),
	.A(op[5]));
   INVX1 U187 (.Y(n121),
	.A(op[3]));
   INVX1 U188 (.Y(irwrite[2]),
	.A(n160));
   NAND2X1 U189 (.Y(n160),
	.B(state[1]),
	.A(n165));
   NAND2X1 U190 (.Y(n180),
	.B(n128),
	.A(n127));
   INVX1 U191 (.Y(n128),
	.A(irwrite[0]));
   INVX1 U192 (.Y(irwrite[0]),
	.A(n158));
   NAND2X1 U193 (.Y(n158),
	.B(n165),
	.A(n177));
   NAND2X1 U194 (.Y(n168),
	.B(n148),
	.A(state[0]));
   INVX1 U196 (.Y(n127),
	.A(n179));
   INVX1 U197 (.Y(n177),
	.A(state[1]));
   NAND2X1 U198 (.Y(n178),
	.B(n148),
	.A(n149));
   INVX1 U199 (.Y(n148),
	.A(state[2]));
   NAND2X1 U201 (.Y(n207),
	.B(n175),
	.A(n176));
   INVX1 U202 (.Y(n186),
	.A(n198));
   NAND2X1 U203 (.Y(n162),
	.B(n145),
	.A(state[1]));
   INVX1 U204 (.Y(n145),
	.A(state[3]));
   NAND2X1 U205 (.Y(n169),
	.B(n149),
	.A(state[2]));
   INVX1 U206 (.Y(n149),
	.A(state[0]));
   INVX1 U208 (.Y(n155),
	.A(n174));
   NAND2X1 U209 (.Y(n184),
	.B(n130),
	.A(n129));
   INVX1 U210 (.Y(n130),
	.A(op[1]));
   INVX1 U211 (.Y(n129),
	.A(n194));
   NAND2X1 U212 (.Y(n194),
	.B(n132),
	.A(n131));
   INVX1 U213 (.Y(n132),
	.A(op[0]));
   INVX1 U214 (.Y(n131),
	.A(op[4]));
   NAND2X1 U215 (.Y(n193),
	.B(n172),
	.A(n173));
   INVX1 U216 (.Y(n172),
	.A(n157));
   NAND2X1 U217 (.Y(n157),
	.B(state[2]),
	.A(state[0]));
   INVX1 U218 (.Y(n181),
	.A(reset));
   NOR2X1 U219 (.Y(n1),
	.B(n151),
	.A(n209));
   NOR2X1 U220 (.Y(n208),
	.B(n108),
	.A(irwrite[2]));
   NOR2X1 U221 (.Y(n187),
	.B(n153),
	.A(op[5]));
   NOR2X1 U222 (.Y(n199),
	.B(n121),
	.A(n155));
   NOR2X1 U223 (.Y(n205),
	.B(n155),
	.A(n193));
   NOR2X1 U224 (.Y(pcsource[1]),
	.B(n157),
	.A(n166));
   NOR2X1 U225 (.Y(irwrite[3]),
	.B(n159),
	.A(n169));
   NOR2X1 U226 (.Y(n165),
	.B(n168),
	.A(state[3]));
   NOR2X1 U227 (.Y(n173),
	.B(state[1]),
	.A(state[3]));
   NOR2X1 U228 (.Y(aluop[1]),
	.B(n178),
	.A(n170));
   NOR2X1 U229 (.Y(FE_OFN0_pcsource_0_),
	.B(n166),
	.A(n169));
   NOR2X1 U230 (.Y(n198),
	.B(n162),
	.A(n169));
   NOR2X1 U231 (.Y(n161),
	.B(pcsource[0]),
	.A(aluop[1]));
   NOR2X1 U232 (.Y(irwrite[1]),
	.B(n178),
	.A(n162));
   NOR2X1 U233 (.Y(memwrite),
	.B(n166),
	.A(n168));
   NOR2X1 U234 (.Y(n182),
	.B(n164),
	.A(n165));
   NOR2X1 U235 (.Y(memtoreg),
	.B(n166),
	.A(n178));
   NOR2X1 U236 (.Y(regdst),
	.B(n168),
	.A(n170));
   NOR2X1 U237 (.Y(n174),
	.B(n184),
	.A(op[2]));
   NOR2X1 U238 (.Y(n176),
	.B(n186),
	.A(n155));
   XOR2X1 U239 (.Y(n175),
	.B(op[3]),
	.A(op[5]));
   AOI22X1 U240 (.Y(n179),
	.D(n177),
	.C(n207),
	.B(n178),
	.A(n207));
   AOI22X1 U241 (.Y(n20),
	.D(n180),
	.C(n181),
	.B(n205),
	.A(n181));
   NOR2X1 U242 (.Y(n191),
	.B(state[3]),
	.A(reset));
   OAI22X1 U243 (.Y(n188),
	.D(n193),
	.C(n185),
	.B(n186),
	.A(n187));
   NOR2X1 U244 (.Y(n190),
	.B(n188),
	.A(n189));
   NOR2X1 U245 (.Y(n196),
	.B(n204),
	.A(n193));
   NOR2X1 U246 (.Y(n195),
	.B(reset),
	.A(n194));
   NOR2X1 U247 (.Y(n3),
	.B(n202),
	.A(n203));
   AOI22X1 U248 (.Y(n210),
	.D(op[1]),
	.C(n203),
	.B(op[2]),
	.A(n203));
endmodule

