/*
###############################################################
#  Generated by:      Cadence Encounter 13.13-s017_1
#  OS:                Linux x86_64(Host ID lab2-23)
#  Generated on:      Tue Nov 18 17:41:13 2014
#  Design:            controller
#  Command:           saveNetlist controller_edi.v
###############################################################
*/
module controller (
	clk, 
	reset, 
	op, 
	zero, 
	memread, 
	memwrite, 
	alusrca, 
	memtoreg, 
	iord, 
	pcen, 
	regwrite, 
	regdst, 
	pcsource, 
	alusrcb, 
	aluop, 
	irwrite);
   input clk;
   input reset;
   input [5:0] op;
   input zero;
   output memread;
   output memwrite;
   output alusrca;
   output memtoreg;
   output iord;
   output pcen;
   output regwrite;
   output regdst;
   output [1:0] pcsource;
   output [1:0] alusrcb;
   output [1:0] aluop;
   output [3:0] irwrite;

   // Internal wires
   wire clk__L1_N0;
   wire FE_OFN1_n197;
   wire FE_OFN0_n198;
   wire n1;
   wire n3;
   wire n7;
   wire n20;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n111;
   wire n112;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n121;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n168;
   wire n170;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n203;
   wire n204;
   wire n205;
   wire n207;
   wire n208;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire [3:0] state;

   BUFX8 clk__L1_I0 (.Y(clk__L1_N0),
	.A(clk));
   BUFX4 FE_OFC1_n197 (.Y(FE_OFN1_n197),
	.A(n197));
   BUFX4 FE_OFC0_n198 (.Y(FE_OFN0_n198),
	.A(n198));
   DFF2 state_reg_1_ (.D(n20),
	.CLK(clk__L1_N0),
	.CLRB(n7),
	.QB(state[1]));
   DFF2 state_reg_3_ (.D(n3),
	.CLK(clk__L1_N0),
	.CLRB(n7),
	.QB(state[3]));
   DFF2 state_reg_2_ (.D(n1),
	.CLK(clk__L1_N0),
	.CLRB(n7),
	.QB(state[2]));
   DFF2 state_reg_0_ (.D(n102),
	.CLK(clk__L1_N0),
	.CLRB(n7),
	.QB(n151),
	.Q(state[0]));
   TIEHI U120 (.Y(n7));
   NAND2X2 U121 (.Y(n119),
	.B(state[2]),
	.A(state[0]));
   NAND2X2 U122 (.Y(n211),
	.B(n117),
	.A(n193));
   INVX8 U123 (.Y(n193),
	.A(n119));
   NAND2X1 U124 (.Y(iord),
	.B(n168),
	.A(n216));
   INV1 U125 (.Y(n168),
	.A(memwrite));
   NAND2X1 U126 (.Y(regwrite),
	.B(n159),
	.A(n162));
   INV1 U127 (.Y(n159),
	.A(memtoreg));
   NAND2X1 U130 (.Y(n162),
	.B(n161),
	.A(n160));
   NAND2X1 U131 (.Y(n160),
	.B(n189),
	.A(n190));
   NAND2X1 U132 (.Y(alusrcb[1]),
	.B(n207),
	.A(n211));
   BUFX4 U134 (.Y(aluop[0]),
	.A(pcsource[0]));
   NAND2X1 U135 (.Y(alusrca),
	.B(n207),
	.A(n183));
   INV1 U137 (.Y(n188),
	.A(n165));
   NAND2X1 U138 (.Y(n165),
	.B(n164),
	.A(n163));
   NAND2X1 U140 (.Y(n163),
	.B(pcsource[0]),
	.A(zero));
   NAND2X1 U141 (.Y(n187),
	.B(n118),
	.A(state[3]));
   NAND2X1 U143 (.Y(n186),
	.B(n136),
	.A(n166));
   NAND2X1 U144 (.Y(n201),
	.B(n200),
	.A(n222));
   NAND2X1 U146 (.Y(n102),
	.B(n103),
	.A(n106));
   NAND2X1 U147 (.Y(n103),
	.B(n104),
	.A(n105));
   INV1 U148 (.Y(n106),
	.A(n107));
   NAND2X1 U149 (.Y(n107),
	.B(n108),
	.A(n111));
   INV1 U150 (.Y(n108),
	.A(n109));
   NAND2X1 U151 (.Y(n109),
	.B(n152),
	.A(n210));
   NAND2X1 U154 (.Y(n152),
	.B(n151),
	.A(n150));
   NAND2X1 U155 (.Y(n150),
	.B(state[2]),
	.A(state[1]));
   NAND2X1 U156 (.Y(n111),
	.B(n112),
	.A(n147));
   NAND2X1 U159 (.Y(n147),
	.B(n146),
	.A(n145));
   INV1 U160 (.Y(n146),
	.A(n205));
   NAND2X1 U161 (.Y(n145),
	.B(n220),
	.A(op[2]));
   NAND2X1 U162 (.Y(n139),
	.B(n133),
	.A(n137));
   NAND2X1 U164 (.Y(n137),
	.B(n216),
	.A(n217));
   NAND2X1 U165 (.Y(n216),
	.B(n185),
	.A(n193));
   INV1 U166 (.Y(n217),
	.A(n142));
   NAND2X1 U167 (.Y(n142),
	.B(n141),
	.A(n140));
   NAND2X1 U168 (.Y(n198),
	.B(n174),
	.A(n151));
   NAND2X1 U170 (.Y(n191),
	.B(state[1]),
	.A(state[3]));
   NAND2X1 U171 (.Y(n140),
	.B(n105),
	.A(n215));
   INV1 U174 (.Y(n219),
	.A(n144));
   NAND2X1 U175 (.Y(n144),
	.B(n112),
	.A(n124));
   INV1 U176 (.Y(n124),
	.A(n125));
   NAND2X1 U177 (.Y(n125),
	.B(n213),
	.A(n126));
   INV1 U178 (.Y(n126),
	.A(n127));
   NAND2X1 U179 (.Y(n127),
	.B(n128),
	.A(n143));
   INV1 U180 (.Y(n128),
	.A(n220));
   NAND2X1 U181 (.Y(n143),
	.B(op[1]),
	.A(op[2]));
   NAND2X1 U182 (.Y(n134),
	.B(n133),
	.A(n132));
   INV1 U183 (.Y(n133),
	.A(reset));
   NAND2X1 U184 (.Y(n132),
	.B(n114),
	.A(n115));
   INV1 U185 (.Y(n114),
	.A(n129));
   NAND2X1 U186 (.Y(n129),
	.B(n136),
	.A(n130));
   INV1 U187 (.Y(n130),
	.A(irwrite[2]));
   INV1 U188 (.Y(irwrite[2]),
	.A(n182));
   NAND2X1 U189 (.Y(n182),
	.B(state[1]),
	.A(FE_OFN1_n197));
   NAND2X1 U190 (.Y(n189),
	.B(n174),
	.A(state[0]));
   INV1 U191 (.Y(n174),
	.A(state[2]));
   INV1 U192 (.Y(n115),
	.A(n116));
   NAND2X1 U193 (.Y(n116),
	.B(n135),
	.A(n222));
   NAND2X1 U194 (.Y(n135),
	.B(n220),
	.A(n221));
   NAND2X1 U195 (.Y(n220),
	.B(n149),
	.A(n148));
   INV1 U196 (.Y(n149),
	.A(op[5]));
   INV1 U197 (.Y(n148),
	.A(op[3]));
   INV1 U198 (.Y(n117),
	.A(n181));
   NAND2X1 U199 (.Y(n181),
	.B(n170),
	.A(n118));
   INV1 U201 (.Y(n118),
	.A(state[1]));
   NAND2X1 U202 (.Y(n222),
	.B(n195),
	.A(n196));
   NAND2X1 U203 (.Y(n205),
	.B(n155),
	.A(n154));
   INV1 U204 (.Y(n155),
	.A(op[1]));
   INV1 U205 (.Y(n154),
	.A(n212));
   NAND2X1 U206 (.Y(n212),
	.B(n157),
	.A(n156));
   INV1 U207 (.Y(n157),
	.A(op[0]));
   INV1 U208 (.Y(n156),
	.A(op[4]));
   NAND2X1 U209 (.Y(n207),
	.B(n185),
	.A(n121));
   NAND2X1 U211 (.Y(n184),
	.B(n170),
	.A(state[1]));
   INV1 U212 (.Y(n170),
	.A(state[3]));
   INV1 U213 (.Y(n121),
	.A(n190));
   NAND2X1 U214 (.Y(n190),
	.B(n173),
	.A(state[2]));
   INV1 U215 (.Y(n173),
	.A(state[0]));
   INV1 U216 (.Y(n161),
	.A(n191));
   INV1 U217 (.Y(n164),
	.A(pcsource[1]));
   INV1 U218 (.Y(n218),
	.A(n139));
   INV1 U219 (.Y(n223),
	.A(n134));
   INV1 U221 (.Y(n105),
	.A(n207));
   INV1 U222 (.Y(n141),
	.A(aluop[1]));
   INV1 U223 (.Y(n175),
	.A(n224));
   INV1 U224 (.Y(n166),
	.A(irwrite[1]));
   INV1 U225 (.Y(n185),
	.A(n184));
   NAND2X1 U226 (.Y(pcen),
	.B(n188),
	.A(n203));
   NAND2X1 U227 (.Y(memread),
	.B(n216),
	.A(n203));
   NAND2X1 U229 (.Y(alusrcb[0]),
	.B(n211),
	.A(n203));
   INVX4 U231 (.Y(n199),
	.A(FE_OFN1_n197));
   INV1 U232 (.Y(n104),
	.A(n208));
   INV1 U233 (.Y(n176),
	.A(n215));
   INV1 U234 (.Y(n112),
	.A(n211));
   INV1 U235 (.Y(n136),
	.A(irwrite[3]));
   INV1 U237 (.Y(n204),
	.A(n194));
   NOR2X1 U238 (.Y(n196),
	.B(n204),
	.A(n207));
   NOR2X1 U239 (.Y(n1),
	.B(n175),
	.A(n223));
   NOR2X1 U240 (.Y(n208),
	.B(n176),
	.A(op[5]));
   NOR2X1 U241 (.Y(n215),
	.B(n148),
	.A(n204));
   NOR2X1 U242 (.Y(n221),
	.B(n204),
	.A(n211));
   NOR2X1 U243 (.Y(pcsource[1]),
	.B(n119),
	.A(n187));
   NOR2X1 U244 (.Y(irwrite[0]),
	.B(n199),
	.A(state[1]));
   NOR2X1 U245 (.Y(irwrite[3]),
	.B(n181),
	.A(n190));
   NOR2X1 U246 (.Y(n197),
	.B(n189),
	.A(state[3]));
   NOR2X1 U247 (.Y(aluop[1]),
	.B(FE_OFN0_n198),
	.A(n191));
   NOR2X1 U248 (.Y(pcsource[0]),
	.B(n187),
	.A(n190));
   NOR2X1 U249 (.Y(n183),
	.B(pcsource[0]),
	.A(aluop[1]));
   NOR2X1 U250 (.Y(irwrite[1]),
	.B(FE_OFN0_n198),
	.A(n184));
   NOR2X1 U251 (.Y(memwrite),
	.B(n187),
	.A(n189));
   NOR2X1 U252 (.Y(n203),
	.B(n186),
	.A(FE_OFN1_n197));
   NOR2X1 U253 (.Y(memtoreg),
	.B(n187),
	.A(FE_OFN0_n198));
   NOR2X1 U254 (.Y(regdst),
	.B(n189),
	.A(n191));
   NOR2X1 U255 (.Y(n194),
	.B(n205),
	.A(op[2]));
   XOR2X1 U256 (.Y(n195),
	.B(op[3]),
	.A(op[5]));
   MUX2X1 U257 (.Y(n200),
	.S(state[1]),
	.B(n199),
	.A(FE_OFN0_n198));
   AOI22X1 U258 (.Y(n20),
	.D(n201),
	.C(n133),
	.B(n221),
	.A(n133));
   NOR2X1 U259 (.Y(n210),
	.B(state[3]),
	.A(reset));
   NOR2X1 U260 (.Y(n213),
	.B(reset),
	.A(n212));
   NOR2X1 U261 (.Y(n3),
	.B(n218),
	.A(n219));
   AOI22X1 U262 (.Y(n224),
	.D(op[1]),
	.C(n219),
	.B(op[2]),
	.A(n219));
endmodule

