########################################################
#  Encounter Command script    (Erik Brunvand, 2013)   #
#                                                      #
# This set of scripts works with EDI 13 (F13)          #
#                                                      #
# To use, change everything noted by !! to your own    #
# values. The BASENAME is the name of the macro you're #
# place and routing. It is also the name you should    #
# use for your .conf file. If your macro is named foo  #
# then you need a configuration file named foo.conf    #
# that describes where the .lib, .lef, etc. files are. #
#                                                      #
# There are lots of other things in this file that     #
# you might also like to change that are not           #
# specifically marked with !!. In particular, you      #
# may want to explore different usepct, rowgap, and    #
# aspect settings in the floorplanning. The other      #
# nunbers for things like power rings/stripes you      #
# probably want to keep as the defaults described here #
#                                                      #
########################################################

# set the BASENAME for the config files. This will also 
# be used for the .lib, .lef, .v, and .spef files that 
# are generated by this script
# 
# The BASENAME should be the name of your top macro, and your 
# configuration file should be named <BASENAME>.globals
set BASENAME "controller"

# The following variables are used in fplan.tcl... 
#
# These set the percent utilization target (how dense should
# the cells be placed), and the gap for routing between rows. 
# These are good starting values for small macros. Larger or
# more complex macros will likely need a lowered usepct or
# larger rowgap or both. 
# 
# Note that rowgap and coregap should be divisible by the basic
# grid unit of 0.3 that our AMIC5N/F process uses. 
#
set usepct 0.60   ;# percent utilization in placing cells
set rowgap 15     ;# gap (microns) between pairs of std cell rows
set aspect 0.60   ;# aspect ratio of overall cell (1 is square, 
                   # <1 is landscape, >1 is portrait
set coregap 30.0  ;# gap (microns) between the core and the power rails 

# The following variables are used in pplan.tcl... 
#
# These numbers control the power and ground grid. 
# Note that all these numbers should be divisible by 0.3 so 
# that they fit on the lambda grid (these are good defaults)
set pwidth 9.9     ;# power rail width
set pspace 1.8     ;# power rail space
set swidth 4.8     ;# power stripe width
set sspace 123     ;# power stripe spacing
set soffset 120    ;# power stripe offset to first stripe
set powernet vdd!  ;# the name of the power net
set groundnet gnd! ;# the name of the ground net

# The following variable is used in cts.tcl... 
#
# This is the list of cells that you'd like to use in your
# clock tree. Your cell names may be different! 
set clock_cells [list INV1 INVX2 INVX4 BUFX4]

# The following variable is used in route.tcl... 
#
# set the name of the filler cells: separate the names of the
# filler cells with spaces if you have more than one. 
# Your cell names may be different! 
set fillerCells [list FILL1 FILL4 FILL8]

# the following variable is used in verify.tcl
#
# set the name of the analysis view to use when exporting the .lib
# version of your cell. If you only have one analysis_view, that's
# what goes here! Analysis views are defined in your mmmc.tcl file. 
set default_analysis_view typical_view

#############################################################
# You probably don't need to change anything below this line#
# unless you're modifying the basic flow                    #
#############################################################

#
# Set the flag for EDI to automatically figure out buf, inv, etc.  
set dbgGPSAutoCellFunction 1

# Import design and floorplan
# If the config file is not named $BASENAME.globals, edit this line. 
source $BASENAME.globals 
init_design

# source the files that operate on the circuit
source fplan.tcl  ;# create the floorplan (might be done by hand...)
source pplan.tcl  ;# create the power rings and stripes
source place.tcl  ;# Place the cells and optimize (pre-CTS)
source cts.tcl    ;# Create the clock tree, and optimize (post-CTS)
source route.tcl  ;# Route the design using nanoRoute
source verify.tcl ;# Verify the design and produce output files
#exit





